# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    OPENAI_API_KEY: '%env(OPENAI_API_KEY)%'
    app.jwtsecret: '%env(JWT_SECRET)%'
    stripe_webhook_secret: '%env(resolve:STRIPE_WEBHOOK_SECRET)%'
    stripe_sk: '%env(resolve:STRIPE_SK)%'
    stripe_pk: '%env(resolve:STRIPE_PK)%'
    youtube_script_path: '%kernel.project_dir%/scripts/youtube_service.py'
    youtube_api_key: '%env(resolve:YOUTUBE_API_KEY)%'
    youtube_api_key_2: '%env(resolve:YOUTUBE_API_KEY_2)%'
    youtube_channel_id: '%env(resolve:YOUTUBE_CHANNEL_ID)%'
    python_path: '%env(resolve:PYTHON_PATH)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Configuration explicite du YouTubeScriptService
    App\Service\YouTubeScriptService:
        public: true
        bind:
            $pythonPath: '%python_path%'
            $scriptPath: '%youtube_script_path%'
            $apiKey: '%youtube_api_key%'

    # Service pour TextPreprocessor
    App\Service\TextPreprocessor: ~

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Service\OpenAIService:
        bind:
            $apiKey: '%env(OPENAI_API_KEY)%'

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    App\Controller\Admin\:
        resource: '../src/Controller/Admin/'
        tags: ['controller.service_arguments']
